In [18]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [19]:
import convolutionalNetwork
import dataset

In [20]:
from convolutionalNetwork import ConvNet
network = ConvNet(32, 3)
model = network.initModel(32, 3)


In [23]:
ds = dataset.dataset(256, 256)
train_images = ds['Xtrain']
train_labels = ds['Ytrain']

/home/j/Desktop/DL/ConvolutionalNetwork/dataset.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  'Xtrain' : np.asarray(train_input),


ValueError: could not broadcast input array from shape (256,256,3) into shape (256,256)

In [22]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

model.fit(train_images, train_labels,
          batch_size=100,
          epochs=5,
          verbose=1)

Epoch 1/5
10/10 [==============================] - 12s 1s/step - loss: nan - accuracy: 0.6389       
Epoch 2/5
10/10 [==============================] - 12s 1s/step - loss: nan - accuracy: 0.0000e+00
Epoch 3/5
10/10 [==============================] - 12s 1s/step - loss: nan - accuracy: 0.0000e+00
Epoch 4/5
10/10 [==============================] - 12s 1s/step - loss: nan - accuracy: 0.0000e+00
Epoch 5/5
10/10 [==============================] - 12s 1s/step - loss: nan - accuracy: 0.0000e+00


In [16]:
print(len(train_images))

12


In [17]:
# print(len(train_images))
# model.summary()
print(train_images)

[[[[ 73  87  86]
   [ 72  85  87]
   [ 77  89  93]
   ...
   [ 81  77  77]
   [ 79  76  78]
   [ 87  84  93]]

  [[ 79  91  93]
   [ 71  84  86]
   [ 75  87  91]
   ...
   [ 80  78  78]
   [ 79  77  79]
   [ 85  84  93]]

  [[ 76  86  91]
   [ 74  84  90]
   [ 94 106 110]
   ...
   [ 97  95  94]
   [ 85  86  87]
   [ 83  85  92]]

  ...

  [[ 31  42  40]
   [ 28  34  31]
   [ 20  31  28]
   ...
   [ 38  45  41]
   [ 23  28  29]
   [ 19  27  22]]

  [[ 33  44  42]
   [ 36  41  39]
   [ 43  55  50]
   ...
   [ 28  33  32]
   [ 23  28  32]
   [ 25  32  29]]

  [[ 25  35  36]
   [ 39  45  43]
   [ 48  60  54]
   ...
   [ 17  21  22]
   [ 17  21  26]
   [ 19  25  25]]]


 [[[131 127 117]
   [125 124 114]
   [154 150 136]
   ...
   [189 178 176]
   [173 165 164]
   [179 178 175]]

  [[ 94  95  86]
   [ 91  96  88]
   [103 104  94]
   ...
   [159 165 164]
   [122 137 135]
   [144 147 148]]

  [[112 103  93]
   [110 108  98]
   [135 134 121]
   ...
   [178 173 174]
   [154 162 162]
   [157 168