In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import convolutionalNetwork
import dataset

In [18]:
import numpy as np

In [3]:
from convolutionalNetwork import ConvNet
network = ConvNet(32, 3)
model = network.initModel(32, 3)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 254, 254, 32)      896       
_________________________________________________________________
activation (Activation)      (None, 254, 254, 32)      0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 127, 127, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 125, 125, 32)      9248      
_________________________________________________________________
activation_1 (Activation)    (None, 125, 125, 32)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 62, 62, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 60, 60, 32)        9

In [11]:
ds = dataset.dataset(256, 256)
train_images = ds['Xtrain']
train_labels = ds['Ytrain']

In [28]:
import cv2
for i in range(len(train_images)):
    if len(train_images[i].shape)!=3:
        train_images[i] = cv2.cvtColor(train_images[i],cv2.COLOR_GRAY2RGB)


TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''

In [ ]:
for i in range(len(train_images)):
    train_images[i] = train_images[i] / 255.0

In [ ]:
# print(train_labels[:2000].shape)

MemoryError: Unable to allocate 14.6 GiB for an array with shape (9999, 256, 256, 3) and data type float64

In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

model.fit(train_images, train_labels,
          batch_size=100,
          epochs=5,
          validation_split=0.1,
          verbose=1)

In [16]:
print(len(train_images))

12


In [17]:
# print(len(train_images))
# model.summary()
print(train_images)

[[[[ 73  87  86]
   [ 72  85  87]
   [ 77  89  93]
   ...
   [ 81  77  77]
   [ 79  76  78]
   [ 87  84  93]]

  [[ 79  91  93]
   [ 71  84  86]
   [ 75  87  91]
   ...
   [ 80  78  78]
   [ 79  77  79]
   [ 85  84  93]]

  [[ 76  86  91]
   [ 74  84  90]
   [ 94 106 110]
   ...
   [ 97  95  94]
   [ 85  86  87]
   [ 83  85  92]]

  ...

  [[ 31  42  40]
   [ 28  34  31]
   [ 20  31  28]
   ...
   [ 38  45  41]
   [ 23  28  29]
   [ 19  27  22]]

  [[ 33  44  42]
   [ 36  41  39]
   [ 43  55  50]
   ...
   [ 28  33  32]
   [ 23  28  32]
   [ 25  32  29]]

  [[ 25  35  36]
   [ 39  45  43]
   [ 48  60  54]
   ...
   [ 17  21  22]
   [ 17  21  26]
   [ 19  25  25]]]


 [[[131 127 117]
   [125 124 114]
   [154 150 136]
   ...
   [189 178 176]
   [173 165 164]
   [179 178 175]]

  [[ 94  95  86]
   [ 91  96  88]
   [103 104  94]
   ...
   [159 165 164]
   [122 137 135]
   [144 147 148]]

  [[112 103  93]
   [110 108  98]
   [135 134 121]
   ...
   [178 173 174]
   [154 162 162]
   [157 168